# Site settings
title: Jiří Altman
email: altman.jiri@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jiri-altman.github.io" # the base hostname & protocol for your site
#twitter_username: jaltman
github_username:  jiri-altman

# Build settings
markdown: kramdown

highlighter: pygments
github: [Repository metadata]
safe: true
lsi: false

timezone: Europe/Prague
encoding: utf-8
